import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { execSync } from 'node:child_process';
import {
  rootDir,
  targetDirs,
  codeFiles,
  pkg,
  allSourceFiles,
  testsDirs,
  srcDirs,
  hasTailwind,
  getFiles,
} from './shared';

describe('Level 4: Hygiene & Global Standards @hygiene', () => {
  it('Should forbid em dash in Spanish source code comments', () => {
    allSourceFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const commentRegex = /(\/\/[^\n]*|\/\*[\s\S]*?\*\/|<!--[\s\S]*?-->)/g;
      const comments = content.match(commentRegex) ?? [];
      comments.forEach((comment) => {
        expect(comment, `Em dash (—) found in comment in ${file}: "${comment}"`).not.toContain('—');
      });
    });
  });

  it('Should enforce test file naming conventions', () => {
    const testFiles = allSourceFiles.filter(
      (file) =>
        testsDirs.some((testsDir) => file.startsWith(testsDir)) &&
        !file.includes(`${path.sep}reports${path.sep}`),
    );
    testFiles.forEach((file) => {
      const basename = path.basename(file);
      const validPattern = /\.(test|spec)\.(ts|tsx)$/;
      expect(basename, `Test file ${file} does not follow naming convention`).toMatch(validPattern);
    });
  });

  it('Should forbid debugger statements in source', () => {
    codeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `debugger statement in ${file}`).not.toMatch(/\bdebugger\b/);
    });
  });

  it('Should not use filesystem access in unit tests', () => {
    const unitDirs = targetDirs.map((d: string) => path.join(d, 'tests', 'unit') + path.sep);
    allSourceFiles
      .filter((file: string) => unitDirs.some((unitDir: string) => file.startsWith(unitDir)))
      .forEach((file: string) => {
        const content = fs.readFileSync(file, 'utf8');
        expect(content, `fs access in unit test ${file}`).not.toMatch(/from ['"]node:fs['"]/);
        expect(content, `fs access in unit test ${file}`).not.toMatch(/require\(['"]node:fs['"]\)/);
        expect(content, `fs access in unit test ${file}`).not.toMatch(/from ['"]fs['"]/);
        expect(content, `fs access in unit test ${file}`).not.toMatch(/require\(['"]fs['"]\)/);
      });
  });

  it('Should enforce English-only comments (ASCII)', () => {
    allSourceFiles.forEach((file) => {
      if (file.endsWith('.json') || file.endsWith('.md')) return;
      const content = fs.readFileSync(file, 'utf8');
      const commentRegex = /(\/\/[^\n]*|\/\*[\s\S]*?\*\/|<!--[\s\S]*?-->)/g;
      const comments = content.match(commentRegex);
      if (comments) {
        comments.forEach((comment) => {
          const isAscii = [...comment].every((char) => char.charCodeAt(0) <= 127);
          expect(isAscii, `Non-English comment in ${file}: "${comment}"`).toBe(true);
        });
      }
    });
  });

  it('Should forbid print statements in source', () => {
    codeFiles.forEach((file) => {
      const parts = file.split(path.sep);
      if (parts.includes('.integrity-suite')) return;
      const content = fs.readFileSync(file, 'utf8');
      const consoleRegex = new RegExp('console\\.(log|debug|info|error|warn)', 'i');
      expect(content, `Console usage in ${file}`).not.toMatch(consoleRegex);
    });
  });

  it('Should forbid unresolved tasks in non-markdown files', () => {
    allSourceFiles.forEach((file) => {
      if (file.endsWith('.md') || file.endsWith('.json')) return;
      const content = fs.readFileSync(file, 'utf8');
      const ruleRegex = new RegExp('TO' + 'DO|FIX' + 'ME', 'i');
      expect(content, `Unresolved task in ${file}`).not.toMatch(ruleRegex);
    });
  });

  it('Should not contain AI reasoning artifacts in comments', () => {
    const suspiciousPatterns = [
      /\/\/\s*(this should|not sure|i think|maybe|perhaps|let me|we need to|should work)/i,
      /\/\/\s*added by/i,
      /\/\/\s*generated by/i,
      /\/\/\s*note:/i,
    ];
    codeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const commentRegex = /(\/\/[^\n]*|\/\*[\s\S]*?\*\/)/g;
      const comments = content.match(commentRegex) ?? [];
      comments.forEach((comment) => {
        suspiciousPatterns.forEach((pattern) => {
          expect(comment, `Suspicious AI artifact comment in ${file}: "${comment}"`).not.toMatch(
            pattern,
          );
        });
      });
    });
  });

  it('Should not have trivially passing dummy assertions in test files', () => {
    const metaTestsDir = path.join(rootDir, '.integrity-suite', 'tests');
    const metaTestFiles = getFiles(metaTestsDir).filter((f) => /\.(test|spec)\.(ts|tsx)$/.test(f));
    const testFiles = [
      ...allSourceFiles.filter(
        (file) =>
          testsDirs.some((testsDir) => file.startsWith(testsDir)) &&
          /\.(test|spec)\.(ts|tsx)$/.test(file),
      ),
      ...metaTestFiles,
    ];
    testFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const trivialPatterns = [
        /expect\(true\)\.toBe\(true\)/,
        /expect\(1\)\.toBe\(1\)/,
        /expect\(false\)\.toBe\(false\)/,
      ];
      trivialPatterns.forEach((pattern) => {
        expect(content, `Trivial dummy assertion in ${file}`).not.toMatch(pattern);
      });
    });
  });

  it('Should not have images without alt attribute in HTML/JSX/TSX files', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Image without alt attribute in ${file}`).not.toMatch(
        /<img(?![^>]*\balt\s*=)[^>]*>/i,
      );
    });
  });

  it('Should not have buttons without accessible text in HTML/JSX/TSX files', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const emptyButtons = content.match(/<button(?![^>]*aria-label)[^>]*>\s*<\/button>/gi) ?? [];
      expect(emptyButtons.length, `Button without accessible text or aria-label in ${file}`).toBe(
        0,
      );
    });
  });

  it('Should not have form inputs without associated labels', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Input without label/aria-label in ${file}`).not.toMatch(
        /<input(?![^>]*(?:aria-label|aria-labelledby|id\s*=))[^>]*>/i,
      );
    });
  });

  it('Should have a <main> landmark element in HTML pages', () => {
    const htmlFiles = allSourceFiles.filter((f) => f.endsWith('.html'));
    htmlFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Missing <main> landmark in ${file}`).toMatch(/<main[\s>]/i);
    });
  });

  it('Should not use known low-contrast color pairs in CSS/HTML', () => {
    const styleFiles = allSourceFiles.filter((f) =>
      ['.css', '.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    const lowContrastPattern = /(color\s*:\s*#(?:ccc|999|aaa|bbb|ddd)|color\s*:\s*lightgr[ae]y)/i;
    styleFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Potential low-contrast color in ${file}`).not.toMatch(lowContrastPattern);
    });
  });

  it('Should not use positive tabIndex values in HTML/JSX/TSX files', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const positiveTabIndex = /tabIndex\s*=\s*(?:['"]\s*[1-9]|\{\s*(?:[1-9]|[^}]*[?:]\s*[1-9]))/i;
      expect(
        content,
        `Positive tabIndex in ${file}: disrupts keyboard navigation order`,
      ).not.toMatch(positiveTabIndex);
    });
  });

  it('Should not use non-semantic elements as interactive controls', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(
        content,
        `<div> or <span> with onClick in ${file}: use <button> or <a> instead`,
      ).not.toMatch(/<(?:div|span)[^>]*onClick/i);
    });
  });

  it('Should have lang attribute on <html> element', () => {
    const htmlFiles = allSourceFiles.filter((f) => f.endsWith('.html'));
    htmlFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Missing lang attribute on <html> in ${file}`).toMatch(/<html[^>]+lang\s*=/i);
    });
  });

  it('Buttons and anchors should have pointer cursor', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const elements = content.match(/<(button|a)[^>]*>/gi) ?? [];
      elements.forEach((el) => {
        if (hasTailwind) {
          // Check for cursor-pointer in class or className (supporting JSX/TSX)
          expect(el, `Missing cursor-pointer in ${file}: ${el}`).toMatch(
            /(?:class|className)\s*=\s*(?:["'][^"']*cursor-pointer|\{[^}]*cursor-pointer)/i,
          );
        } else {
          expect(el, `Missing cursor:pointer in ${file}: ${el}`).toMatch(
            /style\s*=\s*(?:["'][^"']*cursor\s*:\s*pointer|\{[^}]*cursor\s*:\s*pointer)/i,
          );
        }
      });
    });
  });

  it('Button content should not be selectable', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const buttons = content.match(/<button[^>]*>/gi) ?? [];
      buttons.forEach((btn) => {
        if (hasTailwind) {
          expect(btn, `Missing select-none in ${file}: ${btn}`).toMatch(
            /(?:class|className)\s*=\s*(?:["'][^"']*select-none|\{[^}]*select-none)/i,
          );
        } else {
          expect(btn, `Missing user-select:none in ${file}: ${btn}`).toMatch(
            /style\s*=\s*(?:["'][^"']*user-select\s*:\s*none|\{[^}]*user-select\s*:\s*none)/i,
          );
        }
      });
    });
  });

  it('External links should use target _blank with rel noopener noreferrer', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const externalLinks = content.match(/<a[^>]*href=["']https?:\/\/[^"']+["'][^>]*>/gi) ?? [];
      externalLinks.forEach((link) => {
        expect(link, `External link without target="_blank" in ${file}`).toMatch(
          /target\s*=\s*(?:["']_blank["']|\{\s*["']_blank["']\s*\})/i,
        );
        expect(link, `External link missing rel="noopener noreferrer" in ${file}`).toMatch(
          /rel\s*=\s*(?:["'][^"']*(noopener|noreferrer)|\{[^}]*(noopener|noreferrer))/i,
        );
      });
    });
  });

  it('Should not have images without loading="lazy"', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Image without loading="lazy" or dynamic loading in ${file}`).not.toMatch(
        /<img(?![^>]*\bloading\s*=\s*(?:["']lazy["']|\{))[^>]*>/i,
      );
    });
  });

  it('Should not have buttons without type attribute', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Button without type attribute in ${file}`).not.toMatch(
        /<button(?![^>]*\btype\s*=)[^>]*>/i,
      );
    });
  });

  it('Should not have text inputs without autocomplete attribute', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Text input without autocomplete in ${file}`).not.toMatch(
        /<input[^>]*type\s*=\s*["']text["'](?![^>]*\bautocomplete\s*=)[^>]*>/i,
      );
    });
  });

  it('Should not have anchors with href="#"', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Anchor with href="#" found in ${file}`).not.toMatch(
        /<a[^>]*href\s*=\s*["']#["'][^>]*>/i,
      );
    });
  });

  it('Should not have anchors inside buttons', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Anchor inside button found in ${file}`).not.toMatch(
        /<button[^>]*>[\s\S]*?<a[^>]*>[\s\S]*?<\/a>[\s\S]*?<\/button>/i,
      );
    });
  });

  it('Should not have images without width and height attributes', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Image missing width or height in ${file}`).not.toMatch(
        /<img(?![^>]*\bwidth\s*=)(?![^>]*\bheight\s*=)[^>]*>/i,
      );
    });
  });

  it('Should not have inputs without name attribute inside forms', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const inputsInForms =
        content.match(/<form[^>]*>[\s\S]*?<input[^>]*>[\s\S]*?<\/form>/gi) ?? [];
      inputsInForms.forEach((inputBlock) => {
        expect(inputBlock, `Input without name attribute inside form in ${file}`).not.toMatch(
          /<input(?![^>]*\bname\s*=)[^>]*>/i,
        );
      });
    });
  });

  it('Should not have images with empty alt without role="presentation"', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Image with empty alt but not marked decorative in ${file}`).not.toMatch(
        /<img[^>]*alt\s*=\s*["']\s*["'](?![^>]*role\s*=\s*["']presentation["'])[^>]*>/i,
      );
    });
  });

  it('Should not have img or button with onClick without tabIndex (keyboard accessibility)', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const clickableElements = content.match(/<(img|button)[^>]*onClick\s*=\s*[^>]+>/gi) ?? [];
      clickableElements.forEach((el) => {
        expect(el, `Clickable element not keyboard-focusable in ${file}: ${el}`).toMatch(
          /\btabIndex\s*=/i,
        );
      });
    });
  });

  it('Labels with for attribute should reference an existing input id', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const labels = content.match(/<label[^>]*for\s*=\s*["'][^"']+["'][^>]*>/gi) ?? [];
      labels.forEach((label) => {
        const match = label.match(/for\s*=\s*["']([^"']+)["']/i);
        if (!match) return;
        const id = match[1];
        expect(content, `Label for="${id}" without matching input id in ${file}`).toMatch(
          new RegExp(`<input[^>]*id=["']${id}["']`, 'i'),
        );
      });
    });
  });

  it('Button elements should not redundantly declare role="button"', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Button with redundant role="button" in ${file}`).not.toMatch(
        /<button[^>]*role\s*=\s*["']button["'][^>]*>/i,
      );
    });
  });

  it('Clickable elements should support keyboard interaction', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const clickable = content.match(/<(div|span|img)[^>]*onClick\s*=\s*[^>]+>/gi) ?? [];
      clickable.forEach((el) => {
        expect(el, `Clickable element without keyboard handler in ${file}`).toMatch(
          /onKey(Down|Up|Press)\s*=/i,
        );
      });
    });
  });

  it('Iframes should have title attribute for accessibility', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Iframe without title attribute in ${file}`).not.toMatch(
        /<iframe(?![^>]*\btitle\s*=)[^>]*>/i,
      );
    });
  });

  it('Tables should include table headers (th)', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const tables = content.match(/<table[^>]*>[\s\S]*?<\/table>/gi) ?? [];
      tables.forEach((table) => {
        expect(table, `Table without <th> headers in ${file}`).toMatch(/<th[^>]*>/i);
      });
    });
  });

  it('Required inputs should include aria-required', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Required input missing aria-required in ${file}`).not.toMatch(
        /<input[^>]*required(?![^>]*aria-required\s*=\s*(?:["']true["']|\{))[^>]*>/i,
      );
    });
  });

  it('Aria-label attributes should not be empty', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Empty aria-label found in ${file}`).not.toMatch(
        /aria-label\s*=\s*["']\s*["']/i,
      );
    });
  });

  it('Interactive elements should not have negative tabIndex', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Interactive element with negative tabIndex in ${file}`).not.toMatch(
        /<(button|a|input|select|textarea)[^>]*tabIndex\s*=\s*["']?-1["']?/i,
      );
    });
  });

  it('Elements should not use invalid aria roles', () => {
    const validRoles = [
      'button',
      'navigation',
      'main',
      'banner',
      'contentinfo',
      'dialog',
      'alert',
      'tab',
      'tabpanel',
      'menu',
      'menuitem',
      'link',
      'presentation',
      'list',
      'listitem',
      'heading',
      'checkbox',
      'radio',
      'switch',
      'slider',
      'progressbar',
      'spinbutton',
      'combobox',
      'option',
      'grid',
      'gridcell',
      'row',
      'rowgroup',
      'columnheader',
      'rowheader',
      'tree',
      'treegrid',
      'treeitem',
      'tooltip',
      'toolbar',
      'status',
      'log',
      'math',
      'feed',
      'article',
      'figure',
      'document',
      'application',
      'separator',
      'scrollbar',
      'none',
      'cell',
      'table',
      'alertdialog',
      'menubar',
      'menuitemcheckbox',
      'menuitemradio',
      'tablist',
      'img',
      'search',
      'form',
      'region',
      'group',
      'complementary',
    ];
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const roles = content.match(/role\s*=\s*["'][^"']+["']/gi) ?? [];
      roles.forEach((roleAttr) => {
        const role = roleAttr.match(/["']([^"']+)["']/)?.[1];
        if (!role) return;
        const isValidRole = validRoles.includes(role);
        expect(isValidRole, `Possibly invalid aria role "${role}" in ${file}`).toBe(true);
      });
    });
  });

  it('Elements with role="button" must be focusable', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const roleButtons = content.match(/<[^>]*role\s*=\s*["']button["'][^>]*>/gi) ?? [];
      roleButtons.forEach((el) => {
        expect(el, `role="button" element not focusable in ${file}`).toMatch(
          /tabIndex\s*=\s*["']?0["']?/i,
        );
      });
    });
  });

  it('Non-anchor elements should not have href attributes', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Non-anchor element with href found in ${file}`).not.toMatch(
        /<(div|span)[^>]*href\s*=/i,
      );
    });
  });

  it('Textarea elements should have accessible labels', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Textarea without label or aria-label in ${file}`).not.toMatch(
        /<textarea(?![^>]*(aria-label|aria-labelledby|id\s*=))[^>]*>/i,
      );
    });
  });

  it('Headings should not skip levels (e.g., h1 to h3)', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const headings = [...content.matchAll(/<h([1-6])[^>]*>/gi)].map((m) => Number(m[1]));
      for (let i = 1; i < headings.length; i++) {
        const prev = headings[i - 1];
        const curr = headings[i];
        expect(curr - prev <= 1, `Heading level skipped in ${file}: h${prev} → h${curr}`).toBe(
          true,
        );
      }
    });
  });

  it('Pages should not contain multiple h1 elements', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const h1s = content.match(/<h1[^>]*>/gi) ?? [];
      expect(h1s.length, `Multiple h1 elements found in ${file}`).toBeLessThanOrEqual(1);
    });
  });

  it('Interactive elements should not have aria-hidden="true"', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Interactive element hidden from screen readers in ${file}`).not.toMatch(
        /<(button|a|input|select|textarea)[^>]*aria-hidden\s*=\s*["']true["'][^>]*>/i,
      );
    });
  });

  it('Images should not use role="button"', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Image incorrectly using role="button" in ${file}`).not.toMatch(
        /<img[^>]*role\s*=\s*["']button["'][^>]*>/i,
      );
    });
  });

  it('Anchors should not contain buttons', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Button nested inside anchor in ${file}`).not.toMatch(
        /<a[^>]*>[\s\S]*?<button[^>]*>[\s\S]*?<\/button>[\s\S]*?<\/a>/i,
      );
    });
  });

  it('Aria-checked should only be used on appropriate roles', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    const validRoles = ['checkbox', 'menuitemcheckbox', 'radio', 'switch'];
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const elements = content.match(/<[^>]*aria-checked\s*=\s*["'][^"']+["'][^>]*>/gi) ?? [];
      elements.forEach((el) => {
        const roleMatch = el.match(/role\s*=\s*["']([^"']+)["']/i);
        const role = roleMatch?.[1];
        expect(
          role !== undefined && validRoles.includes(role),
          `aria-checked used on incompatible role in ${file}: ${el}`,
        ).toBe(true);
      });
    });
  });

  it('Dialog roles should include aria-modal', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Dialog missing aria-modal in ${file}`).not.toMatch(
        /<[^>]*role\s*=\s*["']dialog["'](?![^>]*aria-modal\s*=\s*(?:["']true["']|\{))[^>]*>/i,
      );
    });
  });

  it('Aria-controls should reference an existing id', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const controls = content.match(/aria-controls\s*=\s*["'][^"']+["']/gi) ?? [];
      controls.forEach((attr) => {
        const idMatch = attr.match(/["']([^"']+)["']/);
        if (!idMatch) return;
        const id = idMatch[1];
        expect(content, `aria-controls references missing id "${id}" in ${file}`).toMatch(
          new RegExp(`id=["']${id}["']`, 'i'),
        );
      });
    });
  });

  it('Labels should contain accessible text', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Label without accessible text in ${file}`).not.toMatch(
        /<label[^>]*>\s*<\/label>/i,
      );
    });
  });

  it('Aria-labelledby should reference existing ids', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const attrs = content.match(/aria-labelledby\s*=\s*["'][^"']+["']/gi) ?? [];
      attrs.forEach((attr) => {
        const idStrMatch = attr.match(/["']([^"']+)["']/);
        if (!idStrMatch) return;
        const ids = idStrMatch[1].split(/\s+/);
        ids.forEach((id) => {
          if (!id) return;
          expect(content, `aria-labelledby references missing id "${id}" in ${file}`).toMatch(
            new RegExp(`id=["']${id}["']`, 'i'),
          );
        });
      });
    });
  });

  it('Fieldset elements should contain a legend', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const fieldsets = content.match(/<fieldset[^>]*>[\s\S]*?<\/fieldset>/gi) ?? [];
      fieldsets.forEach((fieldset) => {
        expect(fieldset, `Fieldset missing legend in ${file}`).toMatch(/<legend[^>]*>/i);
      });
    });
  });

  it('Select elements should have associated labels', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Select without label or aria-label in ${file}`).not.toMatch(
        /<select(?![^>]*(aria-label|aria-labelledby|id\s*=))[^>]*>/i,
      );
    });
  });

  it('Progress elements should expose aria-valuenow', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Progress element missing aria-valuenow in ${file}`).not.toMatch(
        /<progress(?![^>]*aria-valuenow\s*=)[^>]*>/i,
      );
    });
  });

  it('Details elements should contain a summary', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const details = content.match(/<details[^>]*>[\s\S]*?<\/details>/gi) ?? [];
      details.forEach((block) => {
        expect(block, `Details element missing summary in ${file}`).toMatch(/<summary[^>]*>/i);
      });
    });
  });

  it('Meter elements should define min and max attributes', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const meters = content.match(/<meter[^>]*>/gi) ?? [];
      meters.forEach((meter) => {
        expect(meter, `Meter missing min attribute in ${file}`).toMatch(
          /\bmin\s*=\s*(?:["'][^"']+["']|\{)/i,
        );
        expect(meter, `Meter missing max attribute in ${file}`).toMatch(
          /\bmax\s*=\s*(?:["'][^"']+["']|\{)/i,
        );
      });
    });
  });

  it('Video elements should include controls attribute', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Video element without controls in ${file}`).not.toMatch(
        /<video(?![^>]*\bcontrols\b)[^>]*>/i,
      );
    });
  });

  it('Audio elements should include controls attribute', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Audio element without controls in ${file}`).not.toMatch(
        /<audio(?![^>]*\bcontrols\b)[^>]*>/i,
      );
    });
  });

  it('Figures containing images should include figcaption', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const figures = content.match(/<figure[^>]*>[\s\S]*?<\/figure>/gi) ?? [];
      figures.forEach((figure) => {
        if (/<img[^>]*>/i.test(figure)) {
          expect(figure, `Figure with image missing figcaption in ${file}`).toMatch(
            /<figcaption[^>]*>/i,
          );
        }
      });
    });
  });

  it('Buttons should have visible text or aria-label', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const emptyButtons = content.match(/<button(?![^>]*aria-label)[^>]*>\s*<\/button>/gi) ?? [];
      expect(emptyButtons.length, `Button without text or aria-label in ${file}`).toBe(0);
    });
  });

  it('Anchor elements should include href attribute', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `Anchor without href found in ${file}`).not.toMatch(
        /<a(?![^>]*href\s*=)[^>]*>/i,
      );
    });
  });

  it('Image alt text should not duplicate adjacent visible text', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const images = content.match(/<img[^>]*alt\s*=\s*["'][^"']+["'][^>]*>/gi) ?? [];
      images.forEach((img) => {
        const altMatch = img.match(/alt\s*=\s*["']([^"']+)["']/i);
        if (!altMatch) return;
        const altText = altMatch[1];
        const nearbyText = new RegExp(`>${altText}<`, 'i');
        expect(content, `Image alt duplicates visible text "${altText}" in ${file}`).not.toMatch(
          nearbyText,
        );
      });
    });
  });

  it('TabIndex should not be greater than 0', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      expect(content, `tabIndex greater than 0 found in ${file}`).not.toMatch(
        /tabIndex\s*=\s*["']?[1-9]\d*["']?/i,
      );
    });
  });

  it('Labels should not contain interactive elements', () => {
    const htmlLikeFiles = allSourceFiles.filter((f) =>
      ['.html', '.tsx', '.jsx'].includes(path.extname(f)),
    );
    htmlLikeFiles.forEach((file) => {
      const content = fs.readFileSync(file, 'utf8');
      const labels = content.match(/<label[^>]*>[\s\S]*?<\/label>/gi) ?? [];
      labels.forEach((label) => {
        expect(label, `Interactive element inside label in ${file}`).not.toMatch(
          /<(button|a|input|select|textarea)[^>]*>/i,
        );
      });
    });
  });

  it('Should not have commented-out code blocks in src/', () => {
    const srcDir = path.join(rootDir, 'src') + path.sep;
    const commentedCodePattern =
      /\/\/\s*(?:const|let|var|function\s+\w|return\s+[\w(]|import\s+[{*\w])/;
    codeFiles
      .filter((f) => f.startsWith(srcDir))
      .forEach((file) => {
        const lines = fs.readFileSync(file, 'utf8').split('\n');
        const hits = lines.filter((l) => commentedCodePattern.test(l));
        expect(hits.length, `Commented-out code in ${file}: ${hits.slice(0, 2).join(' | ')}`).toBe(
          0,
        );
      });
  });

  it('Should have node: imports before relative imports in src/ files', () => {
    const srcDir = path.join(rootDir, 'src') + path.sep;
    codeFiles
      .filter((f) => f.startsWith(srcDir))
      .forEach((file) => {
        const content = fs.readFileSync(file, 'utf8');
        const importLines = content.match(/^import\s.+$/gm) ?? [];
        const lastNodeIdx = importLines.reduce(
          (acc: number, l: string, i: number) => (l.includes("from 'node:") ? i : acc),
          -1,
        );
        const firstRelativeIdx = importLines.findIndex((l: string) => /from\s+['"]\.[.'"]/.test(l));
        if (lastNodeIdx === -1 || firstRelativeIdx === -1) return;
        expect(lastNodeIdx, `node: imports must precede relative imports in ${file}`).toBeLessThan(
          firstRelativeIdx,
        );
      });
  });

  it('Should use axe-core or equivalent for runtime accessibility testing if JSX/TSX is present', () => {
    const hasJsx = allSourceFiles.some((f) => ['.tsx', '.jsx'].includes(path.extname(f)));
    if (!hasJsx) return;

    const deps = { ...(pkg.dependencies || {}), ...(pkg.devDependencies || {}) };
    const a11yTools = ['axe-core', 'vitest-axe', 'jest-axe', 'cypress-axe', '@axe-core/react'];
    const hasA11yTool = a11yTools.some((tool) => deps[tool]);

    expect(
      hasA11yTool,
      'Projects with JSX/TSX should include axe-core or an equivalent for runtime accessibility testing due to regex limitations on dynamic attributes.',
    ).toBe(true);
  });
});
